package com.shield.parentalguard

import android.app.Activity
import android.app.AlertDialog
import android.app.AppOpsManager
import android.content.Context
import android.content.Intent
import android.content.SharedPreferences
import android.content.pm.PackageManager
import android.net.Uri
import android.os.Build
import android.os.Bundle
import android.os.Process
import android.provider.Settings
import android.view.View
import android.widget.Button
import android.widget.EditText
import android.widget.LinearLayout
import android.widget.TextView
import android.widget.Toast
import androidx.core.app.ActivityCompat
import androidx.core.content.ContextCompat
import com.shield.parentalguard.network.PairingApi
import com.shield.parentalguard.security.SecurityKeyStoreManager
import java.util.concurrent.Executors

/**
 * Shield Parental Guard — child device pairing.
 *
 * Redeems a one-time pairCode (generated by the parent in the Mini App)
 * for a long-lived device token via the same Supabase ota-ona-bot edge
 * function the Mini App uses, then stores that token — encrypted at rest
 * via SecurityKeyStoreManager — in SharedPreferences and continues to
 * permissions. See PairingApi for why the old 6-digit family code is no
 * longer accepted here.
 */
class PairingActivity : Activity() {

    private lateinit var prefs: SharedPreferences
    private lateinit var etPairingCode: EditText
    private lateinit var btnPair: Button
    private lateinit var tvPairError: TextView
    private lateinit var layoutPermissions: LinearLayout
    private lateinit var layoutStatus: LinearLayout
    private lateinit var tvStatusText: TextView
    private lateinit var btnGrantLocation: Button
    private lateinit var btnGrantUsage: Button
    private lateinit var btnGrantAccessibility: Button

    private val ioExecutor = Executors.newSingleThreadExecutor()

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_pairing)

        prefs = getSharedPreferences("shield_guard_prefs", Context.MODE_PRIVATE)

        initViews()
        consumePairIntent(intent)
        checkExistingPairing()
    }

    override fun onNewIntent(intent: Intent?) {
        super.onNewIntent(intent)
        if (intent != null) {
            setIntent(intent)
            consumePairIntent(intent)
        }
    }

    private fun initViews() {
        etPairingCode = findViewById(R.id.etPairingCode)
        btnPair = findViewById(R.id.btnPair)
        tvPairError = findViewById(R.id.tvPairError)
        layoutPermissions = findViewById(R.id.layoutPermissions)
        layoutStatus = findViewById(R.id.layoutStatus)
        tvStatusText = findViewById(R.id.tvStatusText)
        btnGrantLocation = findViewById(R.id.btnGrantLocation)
        btnGrantUsage = findViewById(R.id.btnGrantUsage)
        btnGrantAccessibility = findViewById(R.id.btnGrantAccessibility)

        btnPair.setOnClickListener {
            val code = normalizePairCode(etPairingCode.text?.toString())
            if (code.length == 8) {
                bindWithServer(code)
            } else {
                showPairError(
                    "8 belgili kodni kiriting / Введите 8-значный код"
                )
            }
        }

        btnGrantLocation.setOnClickListener { requestLocationPermission() }
        btnGrantUsage.setOnClickListener { requestUsageStatsPermission() }
        btnGrantAccessibility.setOnClickListener { requestAccessibilityPermission() }
    }

    /** Accept a pairCode from shield://pair?code=XXXXXXXX or extras. */
    private fun consumePairIntent(intent: Intent) {
        var raw: String? = intent.getStringExtra("code")
            ?: intent.getStringExtra("pair_code")

        val data: Uri? = intent.data
        if (raw.isNullOrBlank() && data != null) {
            raw = data.getQueryParameter("code") ?: data.lastPathSegment
        }

        val code = normalizePairCode(raw)
        if (code.length == 8) {
            etPairingCode.setText(code)
        }
    }

    // device_pair_codes.code alphabet (07_device_tokens.sql / index.ts):
    // A-Z + 2-9, excluding 0/O/1/I/L so a child can't confuse similar glyphs.
    private val pairCodeAlphabet = "ABCDEFGHJKMNPQRSTUVWXYZ23456789".toSet()

    private fun normalizePairCode(raw: String?): String {
        if (raw.isNullOrBlank()) return ""
        return raw.trim().uppercase().filter { it in pairCodeAlphabet }
    }

    private fun showPairError(message: String) {
        tvPairError.text = message
        tvPairError.visibility = View.VISIBLE
        Toast.makeText(this, message, Toast.LENGTH_SHORT).show()
    }

    private fun clearPairError() {
        tvPairError.text = ""
        tvPairError.visibility = View.GONE
    }

    private fun bindWithServer(code: String) {
        clearPairError()
        btnPair.isEnabled = false
        btnPair.text = "Ulanmoqda... / Подключение..."

        ioExecutor.execute {
            val result = try {
                PairingApi.pairDevice(code)
            } catch (e: Exception) {
                Result.failure(e)
            }

            runOnUiThread {
                btnPair.isEnabled = true
                btnPair.text = getString(R.string.btn_pair_label)

                result.onSuccess { pairing ->
                    savePairing(pairing)
                }.onFailure {
                    showPairError(
                        "Ulanish muvaffaqiyatsiz. Kod noto'g'ri, eskirgan yoki allaqachon ishlatilgan. / " +
                            "Не удалось подключиться. Код неверный, устарел или уже использован."
                    )
                }
            }
        }
    }

    private fun checkExistingPairing() {
        val savedToken = prefs.getString("device_token_enc", null)
        if (!savedToken.isNullOrEmpty()) {
            showPermissionsOrActiveState()
        }
    }

    private fun savePairing(pairing: PairingApi.DevicePairResult) {
        // deviceToken is a long-lived credential (equivalent to a password) —
        // encrypted at rest via the hardware Keystore, never stored in plain text.
        val (encToken, iv) = SecurityKeyStoreManager.encryptData(pairing.deviceToken)
        prefs.edit()
            .putString("device_token_enc", encToken)
            .putString("device_token_iv", iv)
            .putString("family_code", pairing.familyCode)
            .putString("child_id", pairing.childId)
            .putBoolean("is_paired", true)
            .apply()
        clearPairError()
        Toast.makeText(
            this,
            "Qurilma ulandi! / Устройство подключено!",
            Toast.LENGTH_LONG
        ).show()
        showPermissionsOrActiveState()
    }

    private fun showPermissionsOrActiveState() {
        findViewById<LinearLayout>(R.id.layoutCodeInput).visibility = View.GONE
        layoutPermissions.visibility = View.VISIBLE

        val hasLocation = ContextCompat.checkSelfPermission(
            this,
            android.Manifest.permission.ACCESS_FINE_LOCATION
        ) == PackageManager.PERMISSION_GRANTED
        val hasUsage = checkUsageStatsPermission()

        btnGrantLocation.isEnabled = !hasLocation
        btnGrantLocation.text = if (hasLocation) {
            "Lokatsiya faol / Локация активна"
        } else {
            "1. Lokatsiyaga ruxsat / Разрешить локацию"
        }

        btnGrantUsage.isEnabled = !hasUsage
        btnGrantUsage.text = if (hasUsage) {
            "Ekran vaqti faol / Экранное время активно"
        } else {
            "2. Foydalanish ruxsati / Доступ к использованию"
        }

        if (hasLocation && hasUsage) {
            layoutPermissions.visibility = View.GONE
            layoutStatus.visibility = View.VISIBLE
            tvStatusText.text =
                "Qurilma himoyalangan va ulangan!\nУстройство защищено и подключено!"
            startGuardService()
        }
    }

    /**
     * Joylashuv ruxsati — OSHKOR QILISH ekrani bilan birga.
     *
     * Bu ekran ikkita talabga birdan javob beradi:
     *  1) Google Play "prominent disclosure": fon rejimidagi joylashuv va
     *     Accessibility API ishlatilishidan OLDIN nima yig'ilishi va nima
     *     uchun ekani ochiq aytilishi va rozilik olinishi shart.
     *  2) Stalkerware siyosati: kuzatilayotgan odam — ya'ni farzand — buni
     *     bilishi shart. Yashirin kuzatuv bizning tamoyilimizga ham zid.
     */
    private fun requestLocationPermission() {
        AlertDialog.Builder(this)
            .setTitle("Bu telefon ota-onangga ko'rinadi")
            .setMessage(
                "Qalqon AI quyidagilarni yig'adi va FAQAT ota-onangga ko'rsatadi:\n\n" +
                    "📍 Joylashuving — telefon cho'ntagingda, ekran o'chiq bo'lganda ham\n" +
                    "📱 Qaysi ilovalarda qancha vaqt o'tkazganing\n" +
                    "🔋 Batareya darajasi\n\n" +
                    "Yig'ilMAYdi:\n" +
                    "✖️ Yozishmalaring va xabarlaring\n" +
                    "✖️ Parollaring\n" +
                    "✖️ Ekrandagi matn va rasmlar\n\n" +
                    "Bu ilova yashirinmaydi: bildirishnoma doim ko'rinib turadi. " +
                    "Fikringni o'zgartirsang, ota-onang bilan gaplashib o'chirishing mumkin.\n\n" +
                    "Davom etsak, keyingi oynada joylashuvga ruxsat so'raladi."
            )
            .setPositiveButton("Tushundim, roziman") { _, _ ->
                ActivityCompat.requestPermissions(
                    this,
                    arrayOf(
                        android.Manifest.permission.ACCESS_FINE_LOCATION,
                        android.Manifest.permission.ACCESS_COARSE_LOCATION
                    ),
                    1001
                )
            }
            .setNegativeButton("Hozircha yo'q", null)
            .setCancelable(false)
            .show()
    }

    /**
     * Fon rejimidagi joylashuv — ALOHIDA so'raladi.
     *
     * Android 11+ da uni oldingi ruxsat bilan birga so'rab bo'lmaydi: tizim
     * bunday so'rovni jimgina rad etadi. Shuning uchun avval oddiy joylashuv
     * beriladi, so'ng "Doim ruxsat berish" alohida so'raladi — usiz radar
     * telefon qulflangan holda umuman ishlamaydi.
     */
    private fun requestBackgroundLocation() {
        if (Build.VERSION.SDK_INT < Build.VERSION_CODES.Q) return
        val granted = ContextCompat.checkSelfPermission(
            this, android.Manifest.permission.ACCESS_BACKGROUND_LOCATION
        ) == PackageManager.PERMISSION_GRANTED
        if (granted) return

        AlertDialog.Builder(this)
            .setTitle("Yana bitta qadam")
            .setMessage(
                "Ota-onang seni telefon cho'ntagingda turganda ham ko'rishi uchun " +
                    "joylashuvga «Doim ruxsat berish» kerak.\n\n" +
                    "Keyingi oynada «Doim ruxsat berish» ni tanla."
            )
            .setPositiveButton("Davom etish") { _, _ ->
                ActivityCompat.requestPermissions(
                    this,
                    arrayOf(android.Manifest.permission.ACCESS_BACKGROUND_LOCATION),
                    1002
                )
            }
            .setNegativeButton("Keyinroq", null)
            .show()
    }

    override fun onRequestPermissionsResult(
        requestCode: Int,
        permissions: Array<out String>,
        grantResults: IntArray
    ) {
        super.onRequestPermissionsResult(requestCode, permissions, grantResults)
        // Oddiy joylashuv berilgandan keyingina fon ruxsatini so'rash mumkin.
        if (requestCode == 1001 && grantResults.isNotEmpty() &&
            grantResults[0] == PackageManager.PERMISSION_GRANTED
        ) {
            requestBackgroundLocation()
        }
        showPermissionsOrActiveState()
    }

    private fun checkUsageStatsPermission(): Boolean {
        val appOps = getSystemService(Context.APP_OPS_SERVICE) as AppOpsManager
        val mode = if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.Q) {
            appOps.unsafeCheckOpNoThrow(
                AppOpsManager.OPSTR_GET_USAGE_STATS,
                Process.myUid(),
                packageName
            )
        } else {
            @Suppress("DEPRECATION")
            appOps.checkOpNoThrow(
                AppOpsManager.OPSTR_GET_USAGE_STATS,
                Process.myUid(),
                packageName
            )
        }
        return mode == AppOpsManager.MODE_ALLOWED
    }

    private fun requestUsageStatsPermission() {
        startActivity(Intent(Settings.ACTION_USAGE_ACCESS_SETTINGS))
    }

    private fun requestAccessibilityPermission() {
        startActivity(Intent(Settings.ACTION_ACCESSIBILITY_SETTINGS))
    }

    private fun startGuardService() {
        com.shield.parentalguard.ParentalGuardApp.startMonitoring(applicationContext)
    }

    override fun onResume() {
        super.onResume()
        if (prefs.getBoolean("is_paired", false)) {
            showPermissionsOrActiveState()
        }
    }

    override fun onDestroy() {
        ioExecutor.shutdownNow()
        super.onDestroy()
    }
}
